name: CI Build (Dual SDRAM)

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: set -o pipefail && curl --fail --location https://raw.githubusercontent.com/terminator2k2/Build-Automation_MiSTer/refs/heads/main/build.sh | bash -
      env:
        CORE_NAME: Saturn_DS
        COMPILATION_COMMAND: /opt/intelFPGA_lite/quartus/bin/quartus_sh --flow compile Saturn_DS.qpf
        COMPILATION_OUTPUT: output_files/Saturn_DS.rbf
        
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISPATCH_TOKEN: ${{ secrets.BUILD_AUTOMATION_DISPATCH_TOKEN }}
